services:
  api:
    build: .
    image: ghcr.io/kvdomingo/douglas-crawler
    restart: unless-stopped
    init: true
    env_file: .env
    command:
      - >
        poetry install --no-root --with dev;
        exec poetry run fastapi dev --host 0.0.0.0 --port 8000 --reload douglas/api.py;
    ports:
      - '8000:8000'
    volumes:
      - .:/app
      - venv-data:/app/.venv

  db:
    image: bitnami/postgresql:17.1.0-debian-12-r0
    restart: unless-stopped
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - db-data:/bitnami/postgresql

  pgadmin:
    image: dpage/pgadmin4:8.13
    restart: unless-stopped
    env_file: .env
    environment:
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 5000
    volumes:
      - pgadmin-data:/pgadmin
    ports:
      - "5000:5000"

volumes:
  venv-data:
  db-data:
  pgadmin-data:
