apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ .Release.Name }}-configmap'
  labels:
    {{- include "douglas-crawler.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
{{- with .Values.configMap }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
