{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "douglas-crawler.fullname" . }}
  labels:
    {{- include "douglas-crawler.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "douglas-crawler.selectorLabels" . | nindent 6 }}
  minAvailable: {{ .Values.pdb.minAvailable }}
{{- end }}
