apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Release.Name }}-secrets'
  labels:
    {{- include "douglas-crawler.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
    avp.kubernetes.io/path: kv/data/lab/douglas-crawler
{{- with .Values.env }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
